#!/usr/bin/env bash
set -euo pipefail
ROOT=path/to/project/7.function_anno_genes/function_annotation_stats
OUT=$ROOT/output
SAMPLE=genome_M46_2_new
TABLE=$ROOT/03_tables/function_annotation_stats_M46_2_new.csv
path/to/home/anaconda3/bin/python "$ROOT/extract_function_annotation_genelists.py" --output-dir "$OUT" --samples "$SAMPLE" --table "$TABLE"
path/to/home/anaconda3/bin/python - "$TABLE" "$ROOT/03_tables/TableS5_M46_2_new.tsv" <<'PY'
import csv, sys
src, dst = sys.argv[1:]
with open(src, newline='') as f: row=next(csv.DictReader(f))
cols=['Entry','Sample ID','Species','Pfam (%)','InterProScan (%)','KEGG (%)','NR (%)','Swiss-Prot (%)','KOG (%)','eggNOG (%)','TrEMBL (%)','GO (%)','Not annotated (n)','Not annotated (%)']
out={'Entry':'new','Sample ID':'Mfis','Species':'Medicago fischeriana','Not annotated (n)':row['Not annotated Gene number'],'Not annotated (%)':row['Not annotated Percent (%)']}
for label, key in [('Pfam','Pfam'),('InterProScan','Interproscan'),('KEGG','KEGG'),('NR','NR'),('Swiss-Prot','Swiss-Prot'),('KOG','KOG'),('eggNOG','eggNOG'),('TrEMBL','TrEMBL'),('GO','GO')]: out[label+' (%)']=row[key+' Percent (%)']
with open(dst,'w') as f:
    f.write('\t'.join(cols)+'\n')
    f.write('\t'.join(str(out.get(c,'')) for c in cols)+'\n')
PY
cat > "$ROOT/03_tables/M46_2_new_function_annotation_README.txt" <<EOF
Input protein FASTA: path/to/projects_all/pan_genome/X_genome_M46_2/6.genome_annotation_gene_predict/output/4.evm_combind_3_finally/finally.genome.anno.pep
Sample name: $SAMPLE
Annotation outputs: $OUT/{pfam_anno,InterproScan_anno,NR_anno,SwissPort_anno,KOG_anno,TrEMBL_anno,eggNOG_anno}/$SAMPLE
Gene lists and Table S5-style row were generated by extract_function_annotation_genelists.py after all seven queues completed.
EOF
echo "finalized $SAMPLE"
