#!/usr/bin/env bash
set -euo pipefail
# Command list captured for review: 02_cmds/diamond.cmds
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/NR_anno && [[ -s genome_474/genome_474.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/nr.gz.dmnd --query genome_474/genome_474.pep.format --out genome_474/genome_474.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/SwissPort_anno && [[ -s genome_474/genome_474.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_sprot.fasta.gz.dmnd --query genome_474/genome_474.pep.format --out genome_474/genome_474.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/KOG_anno && [[ -s genome_474/genome_474.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/data/database/KOG_database/KOG_dataset.fa.dmnd --query genome_474/genome_474.pep.format --out genome_474/genome_474.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/TrEMBL_anno && [[ -s genome_474/genome_474.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_trembl.fasta.dmnd --query genome_474/genome_474.pep.format --out genome_474/genome_474.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/NR_anno && [[ -s genome_A17/genome_A17.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/nr.gz.dmnd --query genome_A17/genome_A17.pep.format --out genome_A17/genome_A17.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/SwissPort_anno && [[ -s genome_A17/genome_A17.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_sprot.fasta.gz.dmnd --query genome_A17/genome_A17.pep.format --out genome_A17/genome_A17.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/KOG_anno && [[ -s genome_A17/genome_A17.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/data/database/KOG_database/KOG_dataset.fa.dmnd --query genome_A17/genome_A17.pep.format --out genome_A17/genome_A17.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/TrEMBL_anno && [[ -s genome_A17/genome_A17.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_trembl.fasta.dmnd --query genome_A17/genome_A17.pep.format --out genome_A17/genome_A17.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/NR_anno && [[ -s genome_Mpo/genome_Mpo.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/nr.gz.dmnd --query genome_Mpo/genome_Mpo.pep.format --out genome_Mpo/genome_Mpo.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/SwissPort_anno && [[ -s genome_Mpo/genome_Mpo.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_sprot.fasta.gz.dmnd --query genome_Mpo/genome_Mpo.pep.format --out genome_Mpo/genome_Mpo.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/KOG_anno && [[ -s genome_Mpo/genome_Mpo.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/data/database/KOG_database/KOG_dataset.fa.dmnd --query genome_Mpo/genome_Mpo.pep.format --out genome_Mpo/genome_Mpo.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/TrEMBL_anno && [[ -s genome_Mpo/genome_Mpo.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_trembl.fasta.dmnd --query genome_Mpo/genome_Mpo.pep.format --out genome_Mpo/genome_Mpo.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/NR_anno && [[ -s genome_Msa/genome_Msa.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/nr.gz.dmnd --query genome_Msa/genome_Msa.pep.format --out genome_Msa/genome_Msa.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/SwissPort_anno && [[ -s genome_Msa/genome_Msa.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_sprot.fasta.gz.dmnd --query genome_Msa/genome_Msa.pep.format --out genome_Msa/genome_Msa.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/KOG_anno && [[ -s genome_Msa/genome_Msa.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/data/database/KOG_database/KOG_dataset.fa.dmnd --query genome_Msa/genome_Msa.pep.format --out genome_Msa/genome_Msa.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/TrEMBL_anno && [[ -s genome_Msa/genome_Msa.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_trembl.fasta.dmnd --query genome_Msa/genome_Msa.pep.format --out genome_Msa/genome_Msa.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/NR_anno && [[ -s genome_R108/genome_R108.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/nr.gz.dmnd --query genome_R108/genome_R108.pep.format --out genome_R108/genome_R108.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/SwissPort_anno && [[ -s genome_R108/genome_R108.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_sprot.fasta.gz.dmnd --query genome_R108/genome_R108.pep.format --out genome_R108/genome_R108.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/KOG_anno && [[ -s genome_R108/genome_R108.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/data/database/KOG_database/KOG_dataset.fa.dmnd --query genome_R108/genome_R108.pep.format --out genome_R108/genome_R108.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
cd path/to/project/7.function_anno_genes/function_annotation_stats/output/TrEMBL_anno && [[ -s genome_R108/genome_R108.pep.format_blastp.tab ]] || path/to/home/anaconda3/bin/conda run -n biosofeware diamond blastp --threads 30 --db path/to/project/7.function_anno_genes/data/uniprot_trembl.fasta.dmnd --query genome_R108/genome_R108.pep.format --out genome_R108/genome_R108.pep.format_blastp.tab --outfmt 6 --sensitive --evalue 1e-5 --quiet
