bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_395/run_genome_395.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_395.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_436/run_genome_436.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_436.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_457/run_genome_457.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_457.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_468/run_genome_468.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_468.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_474a/run_genome_474a.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_474a.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_482/run_genome_482.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_482.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_M22/run_genome_M22.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_M22.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_Mar/run_genome_Mar.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_Mar.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_Mru/run_genome_Mru.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_Mru.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_Msa2/run_genome_Msa2.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_Msa2.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_ZM4/run_genome_ZM4.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_ZM4.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_410/run_genome_410.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_410.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_454/run_genome_454.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_454.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_461/run_genome_461.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_461.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_472/run_genome_472.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_472.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_474b/run_genome_474b.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_474b.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_A17/run_genome_A17.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_A17.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_M46/run_genome_M46.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_M46.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_Mpo/run_genome_Mpo.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_Mpo.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_Msa1/run_genome_Msa1.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_Msa1.pipeline.log 2>&1
bash path/to/project/N_1.EDTA_single/02_EDTA_single/genome_R108/run_genome_R108.sh > path/to/project/N_1.EDTA_single/logs_singleEDTA/genome_R108.pipeline.log 2>&1
