[karyotype_mapping]
blast = in.blast
blast_reverse = false
gff1 = in.gff1
gff2 = in.gff2
score = 100
evalue = 1e-5
repeat_number = 5
ancestor_top = in.ancestor
the_other_lens = in.lens1
blockinfo = Malbus_aak.ortholog_blocks.1to1.csv
blockinfo_reverse = false
limit_length = 20
the_other_ancestor_file = km_result.txt
