; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
[ DataSettings ]
datatype=snNucleotide
containsCodingNuc=False
missingBaseSymbol=?
identicalBaseSymbol=.
gapSymbol=-
[ ProcessTypes ]
ppDistEst=true
ppPairTaxa=true
[ AnalysisSettings ]
Analysis=Distance Estimation
Scope=Pairs of taxa
Estimate Variance=====================
Variance Estimation Method=None
No. of Bootstrap Replications=Not Applicable
Substitution Model=====================
Substitutions Type=Nucleotide
Model/Method=Kimura 2-parameter model
Substitutions to Include=d: Transitions + Transversions
Rates and Patterns=====================
Rates among Sites=Gamma Distributed (G)
Gamma Parameter=1
Pattern among Lineages=Same (Homogeneous)
Data Subset to Use=====================
Gaps/Missing Data Treatment=Complete deletion
Site Coverage Cutoff (%)=Not Applicable
