[CENH3_input]
file = genome_Mpo_CENH3_vs_Input.q20.rmdup.10000.smooth50000.log2.bw
title = CENH3_input
height = 1
color = red
type = fill
min_value = 0
max_value = 5
nans_to_zeros = true
show_data_range = false
number_of_bins = 5000
summary_method = mean

[spacer]
height = 0.5


[CENH3_only]
file = genome_Mpo_CENH3.map.rmdup.bw
title = CENH3_only
height = 1
color = red
type = fill
min_value = 0
max_value = 100
nans_to_zeros = true
show_data_range = false
number_of_bins = 5000
summary_method = mean

[spacer]
height = 0.5

[input_only]
file = genome_Mpo_Input.map.rmdup.bw
title = input_only
height = 1
color = red
type = fill
min_value = 0
max_value = 100
nans_to_zeros = true
show_data_range = false
number_of_bins = 5000
summary_method = mean


[spacer]
height = 0.5

[CENH3 broadPeak]
file = genome_Mpo.CENH3.q20_peaks.broadPeak.bed
title = CENH3 domain
height = 1
display = collapsed
color = 104,144,193
alpha = 0.2
border_color = none
nans_to_zeros = true

[spacer]
height = 0.5

[Sat346]
file = genome_Mpo_Sat346.80_80.bed
title = Sat346
height = 0.5
color = 104,144,193
alpha = 0.1
border_color = none
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.5

[Sat691_692]
file = genome_Mpo_Sat691_692.80_80.bed
title = Sat691_692
height = 0.5
color = 104,144,193
alpha = 0.1
border_color = none
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.5

[Chromosome]
file = genome_Mpo.chromosome_centromere_track.bed9
title = Chr1
height = 0.45
color = bed_rgb
border_color = black
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.1

[x-axis]
# overlay_previous = yes
where = bottom
height = 0.45
fontsize = 8

[spacer]
height = 0.5

[Repeat Density]
file = genome_Mpo.repeat_density.50000bp.bw
file_type = bigwig
title = Repeat Density
height = 1
color = #D0D0D0
type = fill
min_value = 0
max_value = 1
orientation = inverted
border_color = none
number_of_bins = 5000
summary_method = mean
show_data_range = false
nans_to_zeros = true

[spacer]
height = 0.5

[Gene Density]
file = genome_Mpo.gene_density.50000bp.bw
file_type = bigwig
title = Gene Density
height = 1
color = #D0D0D0
type = fill
min_value = 0
max_value = 200
orientation = inverted
border_color = none
number_of_bins = 5000
summary_method = mean
show_data_range = false
nans_to_zeros = true

[spacer]
height = 0.5

[Methylation Density]
file = genome_Mpo.CpG_methylation_density.50k.bw
title = Methylation Density
height = 0.5
color = #6BA878
type = fill
min_value = 0
max_value = 100
nans_to_zeros = true
orientation = inverted
show_data_range = false
number_of_bins = 5000
summary_method = mean

[spacer]
height = 0.3

[AB compartment]
file = genome_Mpo.AB.100kb.cis.bw
title = Eigv
height = 0.9
color = #D1543F
negative_color = #4C93B5
type = fill
min_value = -0.4
max_value = 0.4
number_of_bins = 5000
nans_to_zeros = true
show_data_range = false
summary_method = mean

[spacer]
height = 0.5

[TAD]
file = genome_Mpo.100000.raw.cool
title = Hi-C contacts
height = 5
depth = 10000000
min_value = 1
max_value = 100
colormap = OrRd
show_masked_bins = true
file_type = hic_matrix
orientation = inverted
