[CENH3_input]
file = path/to/project/10.centromere_analysis/output_all/02_chipseq/genome_474/05_chipseq_signal/genome_474_CENH3_vs_Input.q0.rmdup.100000.smooth500000.log2.bw
title = CENH3_input2
height = 1
color = red
type = fill
min_value = 0
max_value = 3
nans_to_zeros = true
show_data_range = false
number_of_bins = 8000
summary_method = mean

[spacer]
height = 0.5

[CENH3 broadPeak]
file = path/to/project/10.centromere_analysis/output_all/02_chipseq/genome_474/06_chipseq_peak/genome_474_CENH3.q0.rmdup.strict.q5.signal2.broadPeak.bed
title = CENH3 domain
height = 1
display = collapsed
color = 104,144,193
alpha = 0.2
border_color = none
nans_to_zeros = true

[spacer]
height = 0.2

[Sat102]
file = path/to/project/10.centromere_analysis/output_all/05_centromere_define/genome_474.TRASH_bed/genome_474.CentM102.TRASH_array.tol5.merge500.len2000.copy5.den0.20.bed
title = Sat102
height = 0.5
color = 104,144,193
alpha = 1
border_color = none
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.2

[Sat118]
file = path/to/project/10.centromere_analysis/output_all/05_centromere_define/genome_474.TRASH_bed/genome_474.CentM118.TRASH_array.tol5.merge500.len2000.copy5.den0.20.bed
title = Sat118
height = 0.5
color = 104,144,193
alpha = 1
border_color = none
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.2

[Sat179]
file = path/to/project/10.centromere_analysis/output_all/05_centromere_define/genome_474.TRASH_bed/genome_474.CentM179.TRASH_array.tol5.merge500.len2000.copy5.den0.20.bed
title = Sat179
height = 0.5
color = 104,144,193
alpha = 0.1
border_color = none
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.2

[Sat317]
file = path/to/project/10.centromere_analysis/output_all/05_centromere_define/genome_474.TRASH_bed/genome_474.CentM317.TRASH_array.tol5.merge500.len2000.copy5.den0.20.bed
title = Sat317
height = 0.5
color = 104,144,193
alpha = 0.1
border_color = none
display = collapsed
labels = false
file_type = bed 

[spacer]
height = 0.2

[Sat53]
file = path/to/project/10.centromere_analysis/output_all/05_centromere_define/genome_474.TRASH_bed/genome_474.CentM53.TRASH_array.tol5.merge500.len2000.copy5.den0.20.bed
title = Sat53
height = 0.5
color = 104,144,193
alpha = 0.1
border_color = none
display = collapsed
labels = false
file_type = bed 


[spacer]
height = 0.2

[TRF repeats]
file = path/to/project/10.centromere_analysis/output_all/05_centromere_define/genome_474.TRF_peak/all_plot/all.TRF.plot.bed
title = TRF repeats
height = 0.4
display = collapsed
color = 31,119,180
border_color = none
labels = false
file_type = bed

[spacer]
height = 0.2

[Chromosome]
file = genome_474.chromosome_centromere_track.bed9
title = Chr1
height = 0.45
color = bed_rgb
border_color = black
display = collapsed
labels = false
file_type = bed

[spacer]
height = 0.1

[x-axis]
# overlay_previous = yes
where = bottom
height = 0.45
fontsize = 8

[spacer]
height = 0.3

[Repeat Density]
file = genome_474.repeat_density.50000bp.bw
file_type = bigwig
title = Repeat Density
height = 1
color = #D0D0D0
type = fill
min_value = 0
max_value = 1
orientation = inverted
border_color = none
number_of_bins = 5000
summary_method = mean
show_data_range = false
nans_to_zeros = true

[spacer]
height = 0.3

[Gene Density]
file = genome_474.gene_density.50000bp.bw
file_type = bigwig
title = Gene Density
height = 1
color = #D0D0D0
type = fill
min_value = 0
max_value = 200
orientation = inverted
border_color = none
number_of_bins = 5000
summary_method = mean
show_data_range = false
nans_to_zeros = true

[spacer]
height = 0.3

# [Methylation Density]
# file = genome_474.CpG_methylation_density.50k.bw
# title = Methylation Density
# height = 0.8
# color = #6BA878
# type = fill
# min_value = 0
# max_value = 200
# nans_to_zeros = true
# orientation = inverted
# show_data_range = false
# number_of_bins = 5000
# summary_method = mean

[spacer]
height = 0.3

[AB compartment]
file = genome_474.AB.100kb.cis.bw
title = Eigv
height = 0.9
color = #D1543F
negative_color = #4C93B5
type = fill
min_value = -0.4
max_value = 0.4
number_of_bins = 5000
nans_to_zeros = true
show_data_range = false
summary_method = mean

[spacer]
height = 0.3

[TAD]
file = genome_474.100000.raw.cool
title = Hi-C contacts
height = 5
depth = 10000000
min_value = 1
max_value = 70
colormap = OrRd
show_masked_bins = true
file_type = hic_matrix
orientation = inverted

[TAD domains]
file = genome_474.TAD.100kb_domains.bed
file_type = domains
display = triangles
border_color = black
color = none
line_width = 0.5
overlay_previous = share-y
labels = false
title =