[correspondence]
blockinfo = in.blockinfo_raw
lens1 = in.lens1
lens2 = in.lens2
tandem = true
tandem_length = 200
pvalue = 0.05
block_length = 20
multiple = 1
homo = 0,1
ks_area = 0,0.49
ks_hit = 0.5
savefile = Malbus_aak.ortholog_blocks.csv
